/**
 * Project Mock Mms Api
 * Swagger implementation for the `Mock Mms Api` service, leveraging annotations at the controller-method level.
 *
 * OpenAPI spec version: 1.0.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { AuthenticationResponseDTO } from '../model/authenticationResponseDTO';
import { RequestUserLoginLDAPDTO } from '../model/requestUserLoginLDAPDTO';
import { ResponseBaseDTO } from '../model/responseBaseDTO';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class AuthenticationService {

    protected basePath = 'https://localhost:8090/mock-mms-api';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Authentication Service
     * Authentication Service
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAuthenticationFedera(observe?: 'body', reportProgress?: boolean): Observable<AuthenticationResponseDTO>;
    public getAuthenticationFedera(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<AuthenticationResponseDTO>>;
    public getAuthenticationFedera(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<AuthenticationResponseDTO>>;
    public getAuthenticationFedera(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<AuthenticationResponseDTO>(`${this.basePath}/getAuthenticationFedera`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Authentication Service
     * Authentication Service
     * @param request Restituisce il codice fiscale dell&#39;utente tramite LDAP
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAuthenticationLDAP(request?: RequestUserLoginLDAPDTO, observe?: 'body', reportProgress?: boolean): Observable<AuthenticationResponseDTO>;
    public getAuthenticationLDAP(request?: RequestUserLoginLDAPDTO, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<AuthenticationResponseDTO>>;
    public getAuthenticationLDAP(request?: RequestUserLoginLDAPDTO, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<AuthenticationResponseDTO>>;
    public getAuthenticationLDAP(request?: RequestUserLoginLDAPDTO, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<AuthenticationResponseDTO>(`${this.basePath}/getAuthenticationLDAP`,
            request,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Authentication Service
     * Authentication Service
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public logout(observe?: 'body', reportProgress?: boolean): Observable<ResponseBaseDTO>;
    public logout(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ResponseBaseDTO>>;
    public logout(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ResponseBaseDTO>>;
    public logout(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["X-auth"]) {
            headers = headers.set('X-auth', this.configuration.apiKeys["X-auth"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<ResponseBaseDTO>(`${this.basePath}/logoutApp`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
