/**
 * Project Mock Mms Api
 * Swagger implementation for the `Mock Mms Api` service, leveraging annotations at the controller-method level.
 *
 * OpenAPI spec version: 1.0.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ResponseBaseDTO } from './responseBaseDTO';


/**
 * This is one User
 */
export interface UserResponseDTO extends ResponseBaseDTO { 
    /**
     * This is the email of User
     */
    email?: string;
    /**
     * Eventuali altri errori
     */
    errors?: Array<string>;
    /**
     * This is the name of User
     */
    firstName?: string;
    /**
     * This is the lastname of User
     */
    lastname?: string;
    /**
     * Messaggio di errore
     */
    message?: string;
    /**
     * Codice realtivo al risultato, se 0 success altrimenti ≠ 0
     */
    resultCode: number;
    /**
     * Indica se l'operazione è andata a buon fine
     */
    success: boolean;
    /**
     * transaction identification
     */
    transactionId?: string;
    /**
     * Class type
     */
    type: string;
}
