/**
 * Project Mock Mms Api
 * Swagger implementation for the `Mock Mms Api` service, leveraging annotations at the controller-method level.
 *
 * OpenAPI spec version: 1.0.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface UserAuthResponseDTO { 
    /**
     * This is fiscal code of user
     */
    codiceFiscale?: string;
    /**
     * This is the last name of user
     */
    cognome?: string;
    /**
     * This is the name of user
     */
    nome?: string;
    /**
     * This is authentication token
     */
    token?: string;
}
